"""add new fields to the Form model

Revision ID: 234ed52ed10b
Revises: d3a525e7aff3
Create Date: 2025-10-24 12:10:05.441611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234ed52ed10b'
down_revision = 'd3a525e7aff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('organ_donor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('restrictions_corrective_lenses', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('restrictions_corrective_lenses')
        batch_op.drop_column('organ_donor')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
