"""Update Form model to support multiple submissions per link

- Change Form.id to auto-generate unique ID instead of using link_id
- Add link_id field to track which link was used for submission
- Remove Link.used flag logic for group-based forms
- Allow multiple submissions per link for group collections

Revision ID: 325b893cd0bb
Revises: cd3bc31a74f9
Create Date: 2025-11-04 19:05:38.744533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325b893cd0bb'
down_revision = 'cd3bc31a74f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_id', sa.String(length=22), nullable=True))
        batch_op.create_index(batch_op.f('ix_form_link_id'), ['link_id'], unique=False)
        batch_op.create_foreign_key('fk_form_link_id_link', 'link', ['link_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_constraint('fk_form_link_id_link', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_form_link_id'))
        batch_op.drop_column('link_id')

    # ### end Alembic commands ###
