"""Add Group model and update Link/Form for group support

Revision ID: 89a1fbaaf683
Revises: fd8635f571a0
Create Date: 2025-11-04 18:42:30.670317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a1fbaaf683'
down_revision = 'fd8635f571a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('expiration_type', sa.String(length=20), nullable=False),
    sa.Column('expiration_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_form_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key('fk_form_group_id_group', 'group', ['group_id'], ['id'])

    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_link_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key('fk_link_group_id_group', 'group', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_constraint('fk_link_group_id_group', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_link_group_id'))
        batch_op.drop_column('group_id')

    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_constraint('fk_form_group_id_group', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_form_group_id'))
        batch_op.drop_column('group_id')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_name'))
        batch_op.drop_index(batch_op.f('ix_group_created_at'))

    op.drop_table('group')
    # ### end Alembic commands ###
