"""Add remember_token field to User model for persistent login

Revision ID: cd3bc31a74f9
Revises: 89a1fbaaf683
Create Date: 2025-11-04 18:52:12.376350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3bc31a74f9'
down_revision = '89a1fbaaf683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('organ_donor',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('restrictions_corrective_lenses',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remember_token', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_remember_token'), ['remember_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_remember_token'))
        batch_op.drop_column('remember_token')

    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('restrictions_corrective_lenses',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('organ_donor',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)

    # ### end Alembic commands ###
